title: [Mastering Reproducibility - pulling, running and building containerized HPC applications]
description: [Container workshop provided by Tufts Research Technology]

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - hands-on/
encoding: UTF-8
